language: perl

perl:
  - "5.24"
  
install: true
install:
    # manually install items from cpanfile so we can skip BioPerl

    # install the modules just used here
    - cpanm --notest Perl::Tidy
    - cpanm --notest Test::Code::TidyAll